const PREFIX = process.env.PREFIX || '!';

async function execute(sock, msg, args, jid) {
  const page = args[0];

  if (page === '2') {
    await sock.sendMessage(jid, { text: `🤖 *Commands Page 2/3*\n_Type *${PREFIX}help 3* for more_\n\n😂 *Fun & Games*\n${PREFIX}joke — Random joke\n${PREFIX}joke2 — Joke style 2\n${PREFIX}joke3 — Joke style 3\n${PREFIX}pun — Random pun\n${PREFIX}riddle — Riddle\n${PREFIX}trivia — Trivia question\n${PREFIX}hangman — Play hangman\n${PREFIX}tictactoe — Tic tac toe\n${PREFIX}wordle — Play wordle\n${PREFIX}8ball <q> — Magic 8 ball\n${PREFIX}truth — Truth question\n${PREFIX}dare — Dare challenge\n${PREFIX}wyr — Would you rather\n${PREFIX}poll <q> — Create poll\n${PREFIX}choose <a|b> — Choose option\n${PREFIX}roll — Roll dice\n${PREFIX}flip — Flip coin\n${PREFIX}random — Random number\n${PREFIX}rate <thing> — Rate something\n${PREFIX}ship <a> <b> — Ship meter\n${PREFIX}love <name> — Love meter\n${PREFIX}roast <name> — Roast 😂\n${PREFIX}insult <name> — Insult\n${PREFIX}compliment — Compliment\n${PREFIX}pickup — Pickup line\n${PREFIX}hack <target> — Hacker prank\n\n🌟 *Facts & Horoscope*\n${PREFIX}horoscope <sign> — Horoscope\n${PREFIX}zodiac <sign> — Zodiac info\n${PREFIX}fortune — Fortune cookie\n${PREFIX}motivate — Motivation\n${PREFIX}quote — Inspirational quote\n${PREFIX}advice — Random advice\n${PREFIX}fact — Fun fact\n${PREFIX}catfact — Cat fact\n${PREFIX}dogfact — Dog fact\n${PREFIX}numberfact <n> — Number fact\n${PREFIX}pokemon <name> — Pokémon info\n${PREFIX}rhyme <word> — Find rhymes\n${PREFIX}synonym <word> — Synonyms\n${PREFIX}antonym <word> — Antonyms` });
    return;
  }

  if (page === '3') {
    await sock.sendMessage(jid, { text: `🤖 *Commands Page 3/3*\n\n🎵 *Media*\n${PREFIX}play <song> — Send audio\n${PREFIX}video <name> — Send video\n${PREFIX}lyrics <song> — Song lyrics\n${PREFIX}sticker — Image to sticker\n${PREFIX}tts <text> — Text to speech\n${PREFIX}translate <text> — Translate\n\n📱 *Tech & Tools*\n${PREFIX}binary <text> — To binary\n${PREFIX}hex <text> — To hex\n${PREFIX}hash <text> — Hash it\n${PREFIX}encode <text> — Base64 encode\n${PREFIX}decode <text> — Base64 decode\n${PREFIX}wordcount <text> — Count words\n${PREFIX}reverse <text> — Reverse text\n${PREFIX}spell <text> — Spell check\n${PREFIX}app <name> — Google Play\n${PREFIX}uuid — Generate UUID\n${PREFIX}password — Gen password\n${PREFIX}storage — Storage info\n${PREFIX}speed — Speed test\n${PREFIX}ip <address> — IP lookup\n${PREFIX}github <user> — GitHub profile\n${PREFIX}wikipedia <q> — Wikipedia\n${PREFIX}country <name> — Country info\n${PREFIX}qr — Session QR info\n\n👥 *Groups*\n${PREFIX}welcome on/off — Welcome msg\n${PREFIX}goodbye on/off — Goodbye msg\n${PREFIX}tagall <msg> — Tag all\n${PREFIX}groupinfo — Group info\n${PREFIX}kick @user — Kick member\n${PREFIX}promote @user — Make admin\n${PREFIX}demote @user — Remove admin\n${PREFIX}mute — Mute group\n\n👤 *Presence & Status*\n${PREFIX}presence typing/recording/online\n${PREFIX}statusview on/off\n${PREFIX}savestatus — Save status\n${PREFIX}autobio <text> — Set bio\n${PREFIX}afk <reason> — Set AFK\n${PREFIX}antidelete on/off\n${PREFIX}creep — Spy mode` });
    return;
  }

  // Page 1 (default)
  await sock.sendMessage(jid, { text: `🤖 *Bot Commands Page 1/3*\n_Type *${PREFIX}help 2* or *${PREFIX}help 3* for more_\n\n🎯 *General*\n${PREFIX}ping — Bot status\n${PREFIX}alive — Is bot alive?\n${PREFIX}time — Date & time\n${PREFIX}today — Today's info\n\n🤖 *AI & Info*\n${PREFIX}ai <question> — Ask AI anything\n${PREFIX}define <word> — Dictionary\n${PREFIX}wikipedia <q> — Wikipedia\n${PREFIX}country <name> — Country info\n${PREFIX}ip <address> — IP lookup\n${PREFIX}github <user> — GitHub profile\n${PREFIX}speed — Speed test\n\n📖 *Religion*\n${PREFIX}bible <ref> — e.g. John 3:16\n${PREFIX}bible random — Random verse\n${PREFIX}quran <ref> — e.g. 2:255\n${PREFIX}quran random — Random ayah\n\n🌤️ *Utilities*\n${PREFIX}weather <city> — Live weather\n${PREFIX}forecast <city> — Forecast\n${PREFIX}calc <expr> — Calculator\n${PREFIX}math <expr> — Math solver\n${PREFIX}convert <val> — Unit converter\n${PREFIX}temperature <v> — Temp convert\n${PREFIX}weight <val> — Weight convert\n${PREFIX}length <val> — Length convert\n${PREFIX}area <val> — Area convert\n${PREFIX}percentage <v> — Percentage\n${PREFIX}bmi <h> <w> — BMI calc\n${PREFIX}age <date> — Age calc\n${PREFIX}howold <date> — How old?\n${PREFIX}timer <time> — Set timer\n${PREFIX}remind <t> <msg> — Reminder\n${PREFIX}reminders — List reminders\n\n⚽ *Sports & News*\n${PREFIX}sports — Latest sports\n${PREFIX}sports <topic> — By topic\n${PREFIX}news — Latest news` });
}

module.exports = { execute };
